import { H3_PLUGIN_VERSION } from "../../../../canvas-agent/src/plugins/minimax-h3/version";

export const h3PluginManifest = {
    id: "minimax-h3",
    name: "H3导演台",
    version: H3_PLUGIN_VERSION,
    description: "把原画布H3导演台 的视频、角色参考、续段尾帧和生成参数带入新画布。",
    mcp: {
        id: "minimax-h3",
        version: H3_PLUGIN_VERSION,
        tools: [
            { id: "h3_list_models", version: "1.2.0", name: "H3 列出模型", description: "列出 MiniMax H3 可用的模型(unet)与 LoRA 清单。", inputJsonSchema: { type: "object", properties: {} }, annotations: { title: "H3 列出模型", readOnlyHint: true } },
            { id: "h3_get_node", version: "1.2.0", name: "H3 读取画布节点", description: "按节点 id 读取画布上的 MiniMax H3 节点及其片段/参考图配置。", inputJsonSchema: { type: "object", properties: { nodeId: { type: "string", description: "画布节点 id" } }, required: ["nodeId"] }, annotations: { title: "H3 读取画布节点", readOnlyHint: true } },
            { id: "h3_get_clip", version: "1.2.0", name: "H3 读取片段总览", description: "读取指定 H3 Clip 的轻量状态；可通过 include 一次附带提示词、参考或运行参数。", inputJsonSchema: { type: "object", properties: { projectId: { type: "string" }, nodeId: { type: "string" }, segmentId: { type: "string" }, include: { type: "array", items: { type: "string", enum: ["prompt", "references", "runtime"] }, uniqueItems: true } }, required: ["projectId", "nodeId", "segmentId"] }, annotations: { title: "H3 读取片段总览", readOnlyHint: true } },
            { id: "h3_get_clip_prompt", version: "1.0.0", name: "H3 读取片段提示词", description: "按需读取指定 H3 Clip 的语义提示词和最终编译提示词。", inputJsonSchema: { type: "object", properties: { projectId: { type: "string" }, nodeId: { type: "string" }, segmentId: { type: "string" } }, required: ["projectId", "nodeId", "segmentId"] }, annotations: { title: "H3 读取片段提示词", readOnlyHint: true } },
            { id: "h3_get_clip_references", version: "1.0.0", name: "H3 读取片段参考", description: "按需读取指定 H3 Clip 编译后的参考素材、角色组和引用预检问题。", inputJsonSchema: { type: "object", properties: { projectId: { type: "string" }, nodeId: { type: "string" }, segmentId: { type: "string" } }, required: ["projectId", "nodeId", "segmentId"] }, annotations: { title: "H3 读取片段参考", readOnlyHint: true } },
            { id: "h3_get_clip_runtime", version: "1.0.0", name: "H3 读取片段运行参数", description: "按需读取指定 H3 Clip 的模型、采样、尺寸、LoRA 和其他运行参数。", inputJsonSchema: { type: "object", properties: { projectId: { type: "string" }, nodeId: { type: "string" }, segmentId: { type: "string" } }, required: ["projectId", "nodeId", "segmentId"] }, annotations: { title: "H3 读取片段运行参数", readOnlyHint: true } },
            { id: "h3_run_clip", version: "1.3.0", name: "H3 运行单段", description: "通过 Backend H3 执行器运行指定片段，优先使用稳定 segmentId，复用任务、媒体落库和终态回写。", inputJsonSchema: { type: "object", properties: { nodeId: { type: "string", description: "画布节点 id" }, segmentId: { type: "string", description: "片段稳定 id" }, segmentIndex: { type: "integer", description: "兼容旧调用的片段下标;省略则运行首个未完成的片段" }, params: { type: "object", description: "覆盖片段自带参数的生成参数" } }, required: ["nodeId"] }, annotations: { title: "H3 运行单段" } },
            { id: "h3_get_task", version: "1.2.0", name: "H3 查询任务", description: "按任务 id 查询 MiniMax H3 生成任务的状态、进度与结果。", inputJsonSchema: { type: "object", properties: { taskId: { type: "string", description: "任务 id" } }, required: ["taskId"] }, annotations: { title: "H3 查询任务", readOnlyHint: true } },
            { id: "h3_cancel_task", version: "1.2.0", name: "H3 取消任务", description: "取消正在运行的 MiniMax H3 生成任务。", inputJsonSchema: { type: "object", properties: { taskId: { type: "string", description: "任务 id" } }, required: ["taskId"] }, annotations: { title: "H3 取消任务", destructiveHint: true } },
            { id: "h3_update_clip", version: "1.3.0", name: "H3 更新片段", description: "按稳定 segmentId 原子更新画布 H3 节点某个片段的部分字段，并返回 Backend 最新片段。", inputJsonSchema: { type: "object", properties: { nodeId: { type: "string", description: "画布节点 id" }, segmentId: { type: "string", description: "片段稳定 id" }, patch: { type: "object", description: "要合并进该片段的字段" } }, required: ["nodeId", "segmentId", "patch"] }, annotations: { title: "H3 更新片段" } },
            { id: "h3_move_clip", version: "1.0.0", name: "H3 移动片段", description: "按稳定 Clip ID 调整指定 H3 节点内的片段顺序；可移动到另一片段前/后，省略目标时移动到末尾。", inputJsonSchema: { type: "object", properties: { projectId: { type: "string", description: "画布项目 id" }, nodeId: { type: "string", description: "H3 节点 id" }, segmentId: { type: "string", description: "要移动的 Clip 稳定 id" }, beforeSegmentId: { type: "string", description: "移动到此 Clip 前面；与 afterSegmentId 二选一" }, afterSegmentId: { type: "string", description: "移动到此 Clip 后面；与 beforeSegmentId 二选一" } }, required: ["projectId", "nodeId", "segmentId"] }, annotations: { title: "H3 移动片段" } },
            { id: "h3_bind_existing_character_groups", version: "1.0.0", name: "绑定现有角色节点组", description: "从已有 character 画布节点读取完整服装目录，只按当前 Clip 选择启用服装；绝不创建角色节点。", inputJsonSchema: { type: "object", properties: { projectId: { type: "string" }, nodeId: { type: "string" }, segmentId: { type: "string" }, characters: { type: "array", items: { type: "object" } } }, required: ["projectId", "nodeId", "segmentId", "characters"] }, annotations: { title: "绑定现有角色节点组" } },
            { id: "h3_write_storyboard_prompt", version: "1.1.0", name: "H3 写入结构化分镜提示词", description: "按分镜编辑器结构写入单个 Clip；subject_definitions 与 retention_analysis 由当前人物引用按规则生成，重复内容按 SHA-256 缓存跳过。", inputJsonSchema: { type: "object", properties: { projectId: { type: "string" }, nodeId: { type: "string" }, segmentId: { type: "string" }, summary: { type: "string" }, openingDescription: { type: "string" }, shots: { type: "array", minItems: 1, items: { type: "object", properties: { description: { type: "string" }, switchTime: { type: "string" }, transitionType: { type: "string", enum: ["continuous", "cut", "dissolve", "fade_black"] }, pictureBindingId: { type: "string" } }, required: ["description"] } }, overallSoundscape: { type: "string" }, nonDiegeticMusic: { type: "string" } }, required: ["projectId", "nodeId", "segmentId", "openingDescription", "shots", "overallSoundscape", "nonDiegeticMusic"] }, annotations: { title: "H3 写入结构化分镜提示词" } },
            { id: "h3_run_all_clips", version: "1.2.0", name: "H3 运行全部片段", description: "通过 Backend H3 执行器运行所有(或指定的)节点，复用任务、媒体落库和终态回写，不依赖打开画布页面。", inputJsonSchema: { type: "object", properties: { nodeIds: { type: "array", items: { type: "string" }, description: "限定运行的节点 id;省略则运行全部 H3 节点" }, params: { type: "object", description: "覆盖片段自带参数的生成参数" } } }, annotations: { title: "H3 运行全部片段" } },
            { id: "canvas_list_reference_assets", version: "1.0.0", name: "列出项目参考资产", description: "列出项目级参考资产库。", inputJsonSchema: { type: "object", properties: { projectId: { type: "string" } }, required: ["projectId"] }, annotations: { title: "列出项目参考资产", readOnlyHint: true } },
            { id: "canvas_update_reference_asset", version: "1.0.0", name: "更新项目参考资产", description: "新增或更新项目参考资产的主要职责和标签。", inputJsonSchema: { type: "object", properties: { projectId: { type: "string" }, asset: { type: "object" } }, required: ["projectId", "asset"] }, annotations: { title: "更新项目参考资产" } },
            { id: "canvas_analyze_reference_asset", version: "1.0.0", name: "记录参考资产分析", description: "把模型分析出的职责、标签和摘要写入项目参考资产。", inputJsonSchema: { type: "object", properties: { projectId: { type: "string" }, assetId: { type: "string" }, role: { type: "string" }, tags: { type: "array", items: { type: "string" } }, summary: { type: "string" }, model: { type: "string" } }, required: ["projectId", "assetId", "role", "tags", "summary"] }, annotations: { title: "记录参考资产分析" } },
            { id: "h3_set_reference_bindings", version: "1.0.0", name: "设置 Clip 参考绑定", description: "按稳定 binding id 原子替换指定 Clip 的参考绑定，不修改节点位置。", inputJsonSchema: { type: "object", properties: { projectId: { type: "string" }, nodeId: { type: "string" }, segmentId: { type: "string" }, bindings: { type: "array", items: { type: "object" } }, expectedBindings: { type: "array", items: { type: "object" } } }, required: ["projectId", "nodeId", "segmentId", "bindings"] }, annotations: { title: "设置 Clip 参考绑定" } },
            { id: "canvas_validate_generation", version: "1.0.0", name: "生成预检", description: "使用 Backend 实际提交编译器预检提示词和参考素材。", inputJsonSchema: { type: "object", properties: { projectId: { type: "string" }, nodeId: { type: "string" }, segmentId: { type: "string" } }, required: ["projectId", "nodeId", "segmentId"] }, annotations: { title: "生成预检", readOnlyHint: true } },
        ],
    },
} as const;
