export type H3Ref = { url: string; type: "image" | "video" | "audio"; name: string; storageKey?: string; slot?: number; segmentId?: string };

export type H3TaskStatus = "idle" | "queued" | "loading" | "success" | "error" | "cancelled";
export type H3TaskState = { id?: string; status: H3TaskStatus; progress: number; error?: string; output?: H3Ref };
export type H3Pane = "library" | "preview" | "video" | "refs";

export type H3Segment = {
    id: string;
    start?: number;
    prompt?: string;
    duration?: number;
    result?: string;
    resultStorageKey?: string;
    results?: H3Ref[];
    status?: string;
    progress?: number;
    runtimeTaskId?: string;
    taskMode?: string;
    seed?: number | string;
    noiseSeedMode?: "random" | "fixed";
    noiseSeed?: number | string;
    modelName?: string;
    loraName?: string;
    loraStrength?: number;
    loraSlots?: Array<{ name: string; strength: number; enabled: boolean }>;
    solAttnEnabled?: boolean;
    solAttnTau?: number;
    solAttnThresholdType?: string;
    solAttnExactMode?: string;
    solAttnDenseSteps?: number;
    solAttnStepOff?: number;
    solAttnSinkTokens?: number;
    t8Enabled?: boolean;
    t8ResidualThreshold?: number;
    t8StartPercent?: number;
    t8EndPercent?: number;
    t8MaxConsecutiveHits?: number;
    t8CacheDevice?: string;
    t8MetricStride?: number;
    t8Verbose?: boolean;
    sigmaEnabled?: boolean;
    videoSigmaShift?: number;
    audioSigmaShift?: number;
    sigmaMode?: string;
    lowSigmaStart?: number;
    lowSigmaEnd?: number;
    sigmaRefineSteps?: number;
    sigmaCurve?: string;
    manualSigma?: string;
    dualSampling?: boolean;
    dualSamplingRatio?: number;
    dualSampler?: string;
    secondPassEnabled?: boolean;
    firstPassSteps?: number;
    secondPassSteps?: number;
    secondPassMegapixels?: number;
    secondPassUpscaleMethod?: string;
    secondPassDenoise?: number;
    secondPassSampler?: string;
    secondPassScheduler?: string;
    secondPassModel?: string;
    secondPassSigma?: number;
    dedicatedAttention?: string;
    startupMode?: string;
    faceRepairSingle?: boolean;
    faceRepairMulti?: boolean;
    globalRepair?: boolean;
    lowMemoryAttentionHeads?: number;
    reservedVramGb?: number;
    runtimeReserveEnabled?: boolean;
    uniBlockSwapEnabled?: boolean;
    uniBlockSwapBlocks?: number;
    latentUpscaleEnabled?: boolean;
    h3FirstSteps?: number;
    h3SecondSteps?: number;
    h3FullSigma?: string;
    v81ManualSigma?: boolean;
    latentUpscaleModel?: string;
    latentUpscaleMegapixels?: number;
    latentUpscaleAlign?: number;
    latentUpscalePrecision?: string;
    realtimePreviewEnabled?: boolean;
    realtimePreviewLongEdge?: number;
    realtimePreviewFrames?: number;
    realtimePreviewFps?: number;
    realtimePreviewJpegQuality?: number;
    rtxEnabled?: boolean;
    rtxResizeMode?: string;
    rtxScale?: number;
    rtxWidth?: number;
    rtxHeight?: number;
    rtxQuality?: string;
    slaEnabled?: boolean;
    slaSparsity?: number;
    slaBlockSize?: string;
    slaMinSequence?: number;
    slaDenseLastSteps?: number;
    slaProtectAudio?: boolean;
    slaDenseSteps?: string;
    slaBackend?: string;
    slaDisableFp16Accum?: boolean;
    slaStabilizeMotion?: boolean;
    audioDriveMarkers?: string;
    audioDriveSegmentImages?: string;
    audioDriveSegmentStoryboards?: string;
    audioDriveCreative?: string;
    audioDriveExclude?: string;
    audioDriveStart?: number;
    audioDriveEnd?: number;
    teAccel?: boolean;
    noDub?: boolean;
    noCaption?: boolean;
    audioMode?: string;
    audioDenoiseStrength?: number;
    addSourceAsReference?: boolean;
    promptPrimaryAudioOrdinal?: number;
    strictPromptTags?: boolean;
    referenceVideoPolicy?: string;
    refImageSize?: string;
    referenceLongEdge?: number;
    refs?: { image?: H3Ref[]; video?: H3Ref[]; audio?: H3Ref[] };
    refItems?: H3Ref[];
    aspectRatio?: string;
    megapixels?: number;
    videoSteps?: number;
    denoise?: number;
    trimIn?: number;
    trimOut?: number;
    motionContextEnabled?: boolean;
    tailFrameEnabled?: boolean;
    motionContextNoiseEnabled?: boolean;
    motionContextNoiseAlpha?: number;
    motionContextNoiseAlphaEnd?: number;
    motionContextNoiseRampFrames?: number;
    combatLoraWeight?: number;
    cinematicLoraWeight?: number;
    mode?: "t2v" | "i2v" | "fl2v" | "ref2va";
    textEncoder?: string;
    textEncoderType?: string;
    textEncoderDevice?: string;
    videoVae?: string;
    audioVae?: string;
    precision?: string;
    sageAttention?: string;
    allowCompile?: boolean;
    sizeMultiple?: number;
    sampler?: string;
    scheduler?: string;
    steps?: number;
    lockAudio?: boolean;
    audioDrive?: boolean;
    audioDriveFile?: string;
    constantTriggerWord?: string;
    nanfengExpandedSections?: Record<string, boolean>;
};
