export type H3Ref = { url: string; type: "image" | "video" | "audio"; name: string; storageKey?: string; slot?: number };

export type H3TaskStatus = "idle" | "queued" | "loading" | "success" | "error" | "cancelled";
export type H3TaskState = { id?: string; status: H3TaskStatus; progress: number; error?: string; output?: H3Ref };
export type H3Pane = "library" | "preview" | "video" | "refs";

export type H3Segment = {
    id: string;
    start?: number;
    prompt?: string;
    duration?: number;
    result?: string;
    resultStorageKey?: string;
    results?: H3Ref[];
    status?: string;
    progress?: number;
    runtimeTaskId?: string;
    taskMode?: string;
    seed?: number | string;
    noiseSeedMode?: "random" | "fixed";
    noiseSeed?: number | string;
    modelName?: string;
    loraName?: string;
    loraStrength?: number;
    teAccel?: boolean;
    noDub?: boolean;
    noCaption?: boolean;
    audioMode?: string;
    audioDenoiseStrength?: number;
    addSourceAsReference?: boolean;
    promptPrimaryAudioOrdinal?: number;
    strictPromptTags?: boolean;
    referenceVideoPolicy?: string;
    refImageSize?: string;
    refs?: { image?: H3Ref[]; video?: H3Ref[]; audio?: H3Ref[] };
    refItems?: H3Ref[];
    aspectRatio?: string;
    megapixels?: number;
    videoSteps?: number;
    denoise?: number;
    trimIn?: number;
    trimOut?: number;
    motionContextEnabled?: boolean;
    tailFrameEnabled?: boolean;
    motionContextNoiseEnabled?: boolean;
    motionContextNoiseAlpha?: number;
    motionContextNoiseAlphaEnd?: number;
    motionContextNoiseRampFrames?: number;
    combatLoraWeight?: number;
    cinematicLoraWeight?: number;
};
