import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import crypto from "node:crypto";
import { once } from "node:events";
import { BackendDatabase } from "../db.js";
import { startServer } from "../server.js";
import { McpSnapshotExports } from "./mcp-export-routes.js";
import { registerBackendMcpHttpRoutes } from "../mcp.js";
import { Client } from "@modelcontextprotocol/sdk/client/index.js";
import { StreamableHTTPClientTransport } from "@modelcontextprotocol/sdk/client/streamableHttp.js";

test("large MCP exports are immutable authenticated files, never inline snapshots", async t => {
    const originalToken = process.env.INFINITE_CANVAS_BACKEND_TOKEN;
    process.env.INFINITE_CANVAS_BACKEND_TOKEN = "fixture";
    t.after(() => { if (originalToken === undefined) delete process.env.INFINITE_CANVAS_BACKEND_TOKEN; else process.env.INFINITE_CANVAS_BACKEND_TOKEN = originalToken; });
    const root = await fs.mkdtemp(path.join(os.tmpdir(), "mcp-exports-"));
    const exports = new McpSnapshotExports(root);
    const db = new BackendDatabase(":memory:");
    const config = { url: "http://127.0.0.1", token: "fixture", port: 0, origins: [] };
    const { app, stores } = startServer(db, config, { snapshotExports: exports });
    const server = app.listen(0, "127.0.0.1"); await once(server, "listening");
    config.url = `http://127.0.0.1:${(server.address() as any).port}`;
    const routes = registerBackendMcpHttpRoutes(app, config);
    const client = new Client({ name: "export-fixture", version: "1" });
    t.after(async () => { await client.close(); await routes.closeAll(); server.closeAllConnections(); await new Promise<void>(resolve => server.close(() => resolve())); db.close(); await fs.rm(root, { recursive: true, force: true }); });
    const project: any = { id: "p", title: "fixture", revision: 1, nodes: [{ id: "n", type: "text", metadata: { text: "完整正文😀".repeat(100000) } }], connections: [], viewport: { x: 0 } };
    stores.projects.create(project);
    const frozen = stores.projects.get("p")! as unknown as Record<string, unknown>;
    await client.connect(new StreamableHTTPClientTransport(new URL(`${config.url}/mcp`)));
    const result: any = await client.callTool({ name: "canvas_export_snapshot", arguments: { projectId: "p" } });
    assert.equal(result.isError, undefined);
    const receipt = JSON.parse(result.content[0].text).export;
    assert.ok(JSON.stringify(receipt).length < 600);
    assert.equal((await fetch(config.url + receipt.downloadPath)).status, 401);
    const headers = { Authorization: "Bearer fixture" };
    const download = await fetch(config.url + receipt.downloadPath, { headers });
    assert.match(download.headers.get("content-disposition")!, /attachment/);
    const bytes = Buffer.from(await download.arrayBuffer());
    assert.equal(bytes.length, receipt.bytes);
    assert.equal(crypto.createHash("sha256").update(bytes).digest("hex"), receipt.sha256);
    assert.equal(JSON.parse(bytes.toString()).viewport, undefined);
    assert.deepEqual(JSON.parse(bytes.toString()).nodes, project.nodes);
    const updated = await exports.create({ ...project, revision: 2 });
    assert.notEqual(updated.sha256, receipt.sha256);
    assert.deepEqual(await exports.read(receipt.sha256), bytes);
    assert.equal((await exports.create(frozen)).sha256, receipt.sha256);
    assert.equal((await fetch(`${config.url}/mcp/exports/invalid`, { headers })).status, 400);
    assert.equal((await fetch(`${config.url}/mcp/exports/${"0".repeat(64)}`, { headers })).status, 404);
    await assert.rejects(exports.read("../secret"), /INVALID_EXPORT_HASH/);
    console.log(`export projection: ${bytes.length} -> ${Buffer.byteLength(JSON.stringify(receipt))} bytes`);
});
