import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import express from "express";
import { once } from "node:events";
import { BackendDatabase } from "../db.js";
import { createStores } from "../stores/index.js";
import { EpisodeProductionService } from "../drama/production.js";
import { registerDramaProductionRoutes } from "./drama-production-routes.js";
import { registerComfyRoutes } from "./comfy-routes.js";
import { registerBackendMcpHttpRoutes } from "../mcp.js";
import { KNOWN_FIRST_PARTY } from "@basketikun/canvas-agent/plugin-mcp";
import { Client } from "@modelcontextprotocol/sdk/client/index.js";
import { StreamableHTTPClientTransport } from "@modelcontextprotocol/sdk/client/streamableHttp.js";

test("HTTP MCP defaults stay compact while historic source and model catalog remain completely readable", async t => {
    const root = await fs.mkdtemp(path.join(os.tmpdir(), "mcp-payload-contract-"));
    const db = new BackendDatabase(path.join(root, "fixture.sqlite"));
    db.upsertCanvasFolder({ id: "drama", name: "fixture", createdAt: new Date().toISOString(), isDrama: true });
    db.createCanvasProject({ id: "canvas", title: "fixture", nodes: [], connections: [] });
    db.upsertDramaEpisode({ id: "ep", dramaId: "drama", episodeNumber: 1, title: "fixture", synopsis: "", fullPlot: "", canvasId: "canvas" });
    const service = new EpisodeProductionService(db, undefined, root);
    const text = "完整历史剧本😀".repeat(50000);
    service.edit("ep", { operationId: "write", expectedRevision: 0, ops: [{ type: "upsert_scene", scene: { id: "s", heading: "内景", location: "房间", timeOfDay: "夜", blocks: [{ id: "b", kind: "action", text }] } }] });
    service.publish("ep", { operationId: "publish", expectedRevision: 1, stage: "script" });
    const api = express(); api.use(express.json());
    api.get("/plugins/mcp", (_req, res) => res.json({ ok: true, declarations: [{ id: "minimax-h3", enabled: true, version: KNOWN_FIRST_PARTY["minimax-h3"].version, tools: [] }] }));
    api.post("/mcp/observability/events", (_req, res) => res.json({ ok: true }));
    registerDramaProductionRoutes(api, service);
    const config = { url: "http://127.0.0.1", token: "fixture", port: 0, origins: [] };
    registerComfyRoutes({ app: api, config, stores: createStores(db) }, { models: async () => ({ models: Array.from({ length: 10000 }, (_, i) => `H3-${i}`), loras: [], textEncoders: [], videoVaes: [], audioVaes: [], latentUpscaleModels: [], refreshedAt: "fixed" }) } as any);
    const server = api.listen(0, "127.0.0.1"); await once(server, "listening");
    config.url = `http://127.0.0.1:${(server.address() as any).port}`;
    const routes = registerBackendMcpHttpRoutes(api, config);
    const client = new Client({ name: "payload-fixture", version: "1" });
    t.after(async () => { await client.close(); await routes.closeAll(); server.closeAllConnections(); await new Promise<void>(resolve => server.close(() => resolve())); db.close(); await fs.rm(root, { recursive: true, force: true }); });
    await client.connect(new StreamableHTTPClientTransport(new URL(`${config.url}/mcp`)));
    const call = async (name: string, args: Record<string, unknown>) => {
        const result: any = await client.callTool({ name, arguments: args });
        assert.equal(result.isError, undefined, JSON.stringify(result));
        return JSON.parse(result.content[0].text);
    };
    const tools = await client.listTools();
    assert.ok((tools.tools.find(tool => tool.name === "production_get")!.inputSchema.properties as any).ifRevision);
    assert.equal((tools.tools.find(tool => tool.name === "production_get")!.inputSchema.properties as any).view, undefined);
    assert.ok((tools.tools.find(tool => tool.name === "production_get_source")!.inputSchema.required as string[]).includes("sourceSection"));
    assert.ok((tools.tools.find(tool => tool.name === "production_get_artifact")!.inputSchema.required as string[]).includes("targetId"));
    const oldWholeRead = await client.callTool({ name: "production_get", arguments: { kind: "episode", id: "ep", view: "full" } });
    assert.equal(oldWholeRead.isError, true);
    const cachedProduction: any = await (await fetch(`${config.url}/drama/episodes/ep/production`)).json();
    const conditional = await call("production_get", { kind: "episode", id: "ep", ifRevision: cachedProduction.production.revision });
    assert.equal(conditional.production.unchanged, true);
    assert.equal(conditional.production.draft, undefined);
    assert.ok(Buffer.byteLength(JSON.stringify(conditional)) < 2000);
    const staleRead = await call("production_get_source", { kind: "episode", id: "ep", sourceSection: "script", targetIds: ["s"], ifRevision: 0, chunkBytes: 65536 });
    assert.equal(staleRead.production.unchanged, undefined);
    assert.ok(staleRead.production.chunk.text.length > 0);
    const contractTool = tools.tools.find(tool => tool.name === "production_get_contract")!;
    assert.match((contractTool.inputSchema.properties as any).runtimeId.description, /Deprecated/);
    const contract = await call("production_get_contract", { runtimeId: "historical-runtime-no-longer-installed" });
    assert.match(contract.contract.notice, /deprecated/);
    const { resolveAchengEngine } = await import("@basketikun/canvas-agent/skills/acheng");
    assert.equal(contract.contract.engine.runtimeId, resolveAchengEngine().runtimeId);
    assert.equal((tools.tools.find(tool => tool.name === "production_get_version")!.inputSchema.properties as any).view, undefined);
    const summary = await call("production_get_version", { kind: "episode", id: "ep", version: 1 });
    assert.ok(JSON.stringify(summary).length < 3000); assert.equal(summary.version.snapshot.draft.counts.scenes, 1);
    assert.equal(summary.version.snapshot.nextRead.tool, "production_get_version_artifact_index");
    const original = (await (await fetch(`${config.url}/drama/episodes/ep/production/versions/1`)).json() as any).version;
    assert.equal(original.snapshot.scenes[0].blocks[0].text, text, "unselected HTTP reads preserve Web behavior");
    let cursor: string | undefined; let reconstructed = "";
    do {
        const page = await call("production_get_version_source", { kind: "episode", id: "ep", version: 1, sourceSection: "script", targetIds: ["s"], chunkBytes: 65536, cursor });
        reconstructed += page.version.snapshot.chunk.text; cursor = page.version.snapshot.chunk.nextCursor || undefined;
    } while (cursor);
    assert.deepEqual(JSON.parse(reconstructed), original.snapshot.scenes[0]);
    const modelSummary = await call("h3_list_models", {});
    assert.equal(modelSummary.counts.models, 10000); assert.ok(JSON.stringify(modelSummary).length < 1000);
    const filtered = await call("h3_list_models", { view: "entries", categories: ["models"], query: "H3-9999", pageSize: 1 });
    assert.equal(filtered.total, 1); assert.equal(filtered.entries[0].name, "H3-9999");
    console.log(`historical projection: ${Buffer.byteLength(JSON.stringify(original))} -> ${Buffer.byteLength(JSON.stringify(summary))} bytes; selected source section reconstructed`);
});
